set -g prefix C-a

set -g status-position bottom
set -g status-right "%H:%M %d-%b-%y"

set -g visual-activity on

set -g set-titles on
set -g set-titles-string "psmux [#S]"

set -g cursor-style bar
set -g cursor-blink on

set -g allow-predictions on

set -g @catppuccin_flavor 'mocha'
