set -g prefix C-a

set -g status-position bottom
set -g status-right "%H:%M %d-%b-%y"

set -g visual-activity on

set -g set-titles on
set -g set-titles-string "psmux [#S]"

set -g cursor-style bar
set -g cursor-blink on

set -g allow-predictions on

set -g @catppuccin_flavor 'mocha'
set -g @plugin 'psmux-plugins/ppm'
set -g @plugin 'psmux-plugins/psmux-sensible'
set -g @plugin 'psmux-plugins/psmux-pain-control'
set -g @plugin 'psmux-plugins/psmux-theme-catppuccin'
set -g @plugin 'psmux-plugins/psmux-logging'

run '~/.config/psmux/plugins/ppm/ppm.ps1'
run '~/.config/psmux/plugins/psmux-sensible/psmux-sensible.ps1'
run '~/.config/psmux/plugins/psmux-pain-control/psmux-pain-control.ps1'
run '~/.config/psmux/plugins/psmux-theme-catppuccin/psmux-theme-catppuccin.ps1'
run '~/.config/psmux/plugins/psmux-logging/psmux-logging.ps1'
